# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build api`.
# Run the container with `docker run -p 3000:3000 -t api`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system api && \
    adduser --system -G api api

# Copy built code
COPY dist/api api

# Copy Prisma schema
COPY src/prisma ./src/prisma

# Install dependencies
RUN npm --prefix api --omit=dev -f install

# Generate Prisma client from correct schema path
RUN npx --prefix api prisma generate --schema=src/prisma/schema.prisma

RUN chown -R api:api .

USER api

CMD [ "node", "api" ]
