# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build api`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t api`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

# Create app user
RUN addgroup --system api && \
    adduser --system -G api api

# Copy built application
COPY dist/api api

# Copy Prisma schema (required for client generation)
COPY src/prisma ./src/prisma

# Install production dependencies
RUN npm --prefix api --omit=dev -f install

# Generate Prisma client inside /app/api
RUN npx --prefix api prisma generate

# Set permissions
RUN chown -R api:api .

USER api

CMD [ "node", "api" ]
